version: "2"
services:
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: face-search
            MONGO_INITDB_ROOT_PASSWORD: face-search
            MONGO_INITDB_DATABASE: face-search
        volumes:
            - face-search-storage:/data/db
        ports:
            - 27017:27017
             
    face-search:
        image: geoirb/face-search
        environment: 
            STORAGE_CONNECT: mongodb://face-search:face-search@mongo:27017
            CONFIG_FILE: /config/config.yml
        ports: 
            - 8081:8081
        volumes: 
            - ../config/config.yml:/config/config.yml

volumes:
    face-search-storage: