search:
  timeout: 5m
  actions:
  - type: navigate
    params: 
      - https://search4faces.com/vk01/index.html
  - type: click
    params: 
      - upload-button
  - type: set_upload_files
    params: 
      - input[type='file']
  - type: click
    params: 
      - effects-continue--upload
  - type: wait_not_visible
    params: 
      - uppload-container
  - type: click
    params: 
      - search-button
  - type: wait_visible
    params: 
      - div.row.no-gutters
  - type: result_by_id
    params: 
      - search-results1
      # - search-results2
      # - search-results3